[workspace]
members = [
    "simple",
    "vectors",
    "bindings-simple",
    "bindings-vectors",
    "uniffi-bindgen",
]

[workspace.dependencies]
uniffi = { git = "https://github.com/zduny/uniffi-rs", rev = "e786bda" }
# uniffi = { path = "../uniffi-rs/uniffi" }
