[bindings.swift]
generate_module_map = true
cdylib_name = "bindings-vectors"

[bindings.kotlin]
package_name = "org.zduny.vectors"
cdylib_name = "bindings-vectors"

[bindings.python]
cdylib_name = "bindings-vectors"

[bindings.ruby]
cdylib_name = "bindings-vectors"
