[bindings]
doc_comments = true

[bindings.swift]
generate_module_map = true
cdylib_name = "bindings_simple"

[bindings.kotlin]
package_name = "org.zduny.simple"
cdylib_name = "bindings_simple"

[bindings.python]
cdylib_name = "bindings_simple"

[bindings.ruby]
cdylib_name = "bindings_simple"
